### PR TITLE
Fix sending to img2img

### PR DESCRIPTION
**Pull request by AlUlkesh**
The current pull request #51 seems to fix the problem only for some people some of the time.

This version fixes it for everyone who has tried it. #69

### CODE REVIEW

**Comment by WozniakMac** [comment]
Can we merge this?

**Comment by NoCrypt** [comment]
Oh sh*t, I've debugged this for 6 hours straight, **found the exact same solution.** Should have checked pull request before lmao

**Comment by AlUlkesh** [comment]
Well, glad to hear you came to the same conclusion.

**Comment by tyemirov** [comment]
Is this repo abandoned? @yfszzx

**Comment by tyemirov** [comment]
I have removed the existing `stable-diffusion-webui-images-browser` folder, and used @AlUlkesh repo to manually install the fixed version

image

**Comment by catboxanon** [comment]
Might want to re-open this PR on another branch because it changes a lot more than advertised now.

**Comment by AlUlkesh** [comment]
@catboxanon Yes, you're right. I hadn't thought about someone only wanting this fix now. New PR is here: #84

**Pull request closed without merging**
